
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLUMN COMMA DIRECTIVE IMMEDIATE LABEL LPAREN NEWLINE OPCODE REGISTER RPARENprogram : statementprogram : LABEL COLUMN NEWLINEprogram : NEWLINE\n| statement : DIRECTIVE LABEL NEWLINEstatement : DIRECTIVE IMMEDIATE NEWLINEstatement : DIRECTIVE NEWLINEstatement : OPCODE register COMMA register COMMA register NEWLINEstatement : OPCODE register COMMA register COMMA IMMEDIATE NEWLINEstatement : OPCODE register COMMA IMMEDIATE LPAREN register RPAREN NEWLINEstatement : OPCODE register COMMA IMMEDIATE NEWLINEstatement : OPCODE register COMMA LABEL NEWLINEstatement : OPCODE register COMMA register COMMA LABEL NEWLINEregister : REGISTERstatement : NEWLINE'
    
_lr_action_items = {'LABEL':([0,5,16,20,],[3,8,19,26,]),'NEWLINE':([0,5,7,8,10,12,18,19,24,25,26,31,],[4,9,13,14,15,-14,22,23,28,29,30,32,]),'$end':([0,1,2,4,9,13,14,15,22,23,28,29,30,32,],[-4,0,-1,-3,-7,-2,-5,-6,-11,-12,-8,-9,-13,-10,]),'DIRECTIVE':([0,],[5,]),'OPCODE':([0,],[6,]),'COLUMN':([3,],[7,]),'IMMEDIATE':([5,16,20,],[10,18,25,]),'REGISTER':([6,16,20,21,],[12,12,12,12,]),'COMMA':([11,12,17,],[16,-14,20,]),'RPAREN':([12,27,],[-14,31,]),'LPAREN':([18,],[21,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statement':([0,],[2,]),'register':([6,16,20,21,],[11,17,24,27,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statement','program',1,'p_program_statement','parser.py',28),
  ('program -> LABEL COLUMN NEWLINE','program',3,'p_program_label','parser.py',35),
  ('program -> NEWLINE','program',1,'p_program_empty','parser.py',45),
  ('program -> <empty>','program',0,'p_program_empty','parser.py',46),
  ('statement -> DIRECTIVE LABEL NEWLINE','statement',3,'p_statement_directive_symbol','parser.py',60),
  ('statement -> DIRECTIVE IMMEDIATE NEWLINE','statement',3,'p_statement_directive_imm','parser.py',70),
  ('statement -> DIRECTIVE NEWLINE','statement',2,'p_statement_directive_single','parser.py',80),
  ('statement -> OPCODE register COMMA register COMMA register NEWLINE','statement',7,'p_statement_R','parser.py',93),
  ('statement -> OPCODE register COMMA register COMMA IMMEDIATE NEWLINE','statement',7,'p_statement_I_S_SB','parser.py',111),
  ('statement -> OPCODE register COMMA IMMEDIATE LPAREN register RPAREN NEWLINE','statement',8,'p_statement_load_store_offset','parser.py',142),
  ('statement -> OPCODE register COMMA IMMEDIATE NEWLINE','statement',5,'p_statement_U_UJ','parser.py',167),
  ('statement -> OPCODE register COMMA LABEL NEWLINE','statement',5,'p_statement_UJ_LABEL','parser.py',194),
  ('statement -> OPCODE register COMMA register COMMA LABEL NEWLINE','statement',7,'p_statement_SB_LABEL','parser.py',207),
  ('register -> REGISTER','register',1,'p_register','parser.py',236),
  ('statement -> NEWLINE','statement',1,'p_statement_none','parser.py',249),
]
